version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sequelize
    versions:
    - 6.6.2
  - dependency-name: "@types/cors"
    versions:
    - 2.8.10
  - dependency-name: mocha
    versions:
    - 8.3.2
